[project]
name = "kortix"
version = "0.1.0"
description = "Kortix SDK"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["asyncio>=3.4.3", "httpx>=0.28.1"]

[dependency-groups]
dev = ["fastmcp>=2.10.6"]
